### ISSUE TITLE
Scoreboard still fails

### ISSUE THREAD

**Issue by zmbc** [hamsterdam/kawhi#5]
Hey, sorry to bother you (again :laughing:) but I still have a problem.

The example now works fine for me, but the way I was actually trying to use `kawhi` was to get the [stats.nba.com scoreboard](http://stats.nba.com/stats/scoreboardV2?DayOffset=0&LeagueID=00&gameDate=04%2F20%2F2017) endpoint, which still fails for me using this package. I think it might be because the request has no `Referer` header, as that seems to be required.

I totally get that things like this probably change all the time (as it's a very unstable API). Have you considered exporting a pure version of `getSplitRows` so that users of the library can make the request themselves?

**Comment by thunky-monk** [comment]
No problem at all. 

Thank you for acknowledging the inherent fragility.

In the short term:

If you determine that the missing `Referrer` is the issue, I'll add it to the general headers. Alternatively, if you're interested, you're welcome to open a PR.

In the longer term:

I think a pure `getSplitRows` is a good idea :) Otherwise, these things will likely break usages too frequently. Again, you're welcome to open a PR.

**Comment by thunky-monk** [comment]
Hey, was the error the same as #2?

**Comment by thunky-monk** [comment]
Planning to release:
- `0.2.3` with referer #6
- `0.3.0` with new API #10

**Comment by zmbc** [comment]
@thunky-monk Yep, the error was the same.

Thanks for doing all this! :smiley:
